### ISSUE TITLE
can hostname be autopopulated?

### ISSUE THREAD

**Issue by ppbrown** [fujiwara/fluent-plugin-zabbix#21]
Hello,
your docs dont quite make it clear: if you leave the hostname field blank in the configs, will it get autopopulated in the same way that setting

Hostname=

in zabbix_agent.conf  autopopulates it with the OS hostname?

**Comment by fujiwara** [comment]
This plugin sets `host` value from Ruby's `Socket.gethostname` by default.

https://github.com/fujiwara/fluent-plugin-zabbix/blob/fb805a76ec40fb412bf1a04319fb6282d9d66815/lib/fluent/plugin/out_zabbix.rb#L14

**Comment by ppbrown** [comment]
perfect! Thanks so much

(although you might want to make that clearer in the README examples..)
